// Lumevina — server-side service catalog
// GENERATED from index.html + js/booking.js — regenerate with
// the snippet in server/README.md whenever prices change.

export const CATALOG: Record<string, { name: string; price_cents: number; dur_min: number }> = {
  "ageless-grace-facial": { name: "Ageless Grace Facial", price_cents: 24500, dur_min: 60 },
  "lumevina-custom-facial": { name: "Lumevina Custom Facial", price_cents: 19500, dur_min: 60 },
  "custom-facial-dermaplaning": { name: "Lumevina Custom Facial + Dermaplaning", price_cents: 18500, dur_min: 60 },
  "new-client-consultation": { name: "New Client Consultation + Treatment", price_cents: 21500, dur_min: 60 },
  "new-client-consultation-acne": { name: "New Client Consultation + Treatment (Acne Program)", price_cents: 22500, dur_min: 60 },
  "brazilian-wax-mini-vajacial": { name: "Brazilian Wax x Mini Vajacial Package", price_cents: 10000, dur_min: 60 },
  "underarm-wax": { name: "Underarm Wax", price_cents: 2200, dur_min: 30 },
  "gift-certificate-100": { name: "E-Gift Certificate ($100)", price_cents: 10000, dur_min: 0 },
  "couples-facial": { name: "Couples Facial", price_cents: 32500, dur_min: 60 },
  "after-hours-facial": { name: "After Hours Facial Add-On", price_cents: 3200, dur_min: 60 },
  "light-chemical-peel": { name: "Light Chemical Peel", price_cents: 22500, dur_min: 60 },
  "medium-chemical-peel": { name: "Medium Chemical Peel", price_cents: 23500, dur_min: 60 },
  "biorepeel-1": { name: "BioRePeel - 1 Facial Treatment", price_cents: 27000, dur_min: 60 },
  "biorepeel-3": { name: "BioRePeel - 3 Facial Treatments", price_cents: 67000, dur_min: 60 },
  "back-facial-full": { name: "Back Facial - Full", price_cents: 18500, dur_min: 60 },
  "back-facial-half": { name: "Back Facial - Half", price_cents: 14000, dur_min: 60 },
  "monthly-acne-treatment": { name: "Monthly Acne Treatment", price_cents: 19500, dur_min: 60 },
  "biweekly-acne-treatment": { name: "Bi-Weekly Acne Treatment", price_cents: 12000, dur_min: 60 },
  "virtual-consultation": { name: "Virtual Consultation", price_cents: 5500, dur_min: 30 },
  "in-person-consultation": { name: "In-Person Consultation", price_cents: 5500, dur_min: 30 },
  "brow-wax-tweeze": { name: "Brow Wax + Tweeze", price_cents: 2700, dur_min: 30 },
  "upper-lip-wax": { name: "Upper Lip Wax", price_cents: 900, dur_min: 30 },
  "full-face-wax": { name: "Full Face Wax", price_cents: 3800, dur_min: 30 },
  "full-face-wax-cooling-mask": { name: "Full Face Wax + Cooling Mask", price_cents: 5500, dur_min: 60 },
  "sideburn-wax": { name: "Sideburn Wax", price_cents: 2200, dur_min: 30 },
  "hairline-wax": { name: "Hairline Wax", price_cents: 4300, dur_min: 30 },
  "nose-wax": { name: "Nose Wax", price_cents: 900, dur_min: 30 },
  "nostril-wax": { name: "Nostril Wax", price_cents: 1100, dur_min: 30 },
  "full-arm-wax": { name: "Full Arm Wax", price_cents: 6000, dur_min: 30 },
  "half-arm-wax": { name: "Half Arm Wax", price_cents: 3200, dur_min: 30 },
  "full-back-wax": { name: "Full Back Wax", price_cents: 9000, dur_min: 60 },
  "half-back-wax": { name: "Half Back Wax", price_cents: 4800, dur_min: 30 },
  "full-leg-wax": { name: "Full Leg Wax", price_cents: 11000, dur_min: 60 },
  "half-leg-wax": { name: "Half Leg Wax", price_cents: 5500, dur_min: 30 },
  "full-stomach-wax": { name: "Full Stomach Wax", price_cents: 3800, dur_min: 30 },
  "stomach-strip-wax": { name: "Stomach Strip Wax", price_cents: 1100, dur_min: 30 },
  "full-butt-wax": { name: "Full Butt Wax", price_cents: 4300, dur_min: 30 },
  "bikini-line-wax": { name: "Bikini Line Wax", price_cents: 3200, dur_min: 30 },
  "extended-bikini-line": { name: "Extended Bikini Line", price_cents: 5500, dur_min: 30 },
  "brazilian-wax": { name: "Brazilian Wax", price_cents: 8000, dur_min: 30 },
  "first-time-brazilian": { name: "First Time Brazilian", price_cents: 8000, dur_min: 60 },
  "inner-thigh-add-on": { name: "Inner Thigh Add-On", price_cents: 2700, dur_min: 30 },
  "wax-wednesday": { name: "Wax Wednesday (Brazilian)", price_cents: 7000, dur_min: 30 },
};
